### ISSUE TITLE
Rewrite from Java to Kotlin

### ISSUE THREAD

**Issue by iamflorencejay** [OdyseeTeam/odysee-android#11]
Since it is the new release of the Odysee Alpha, the best way to decrease space is to rewrite it on Kotlin. Because less code = less space for the user.

**Comment by iamflorencejay** [comment]
Here is some resources for this:
https://www.xenonstack.com/blog/kotlin-andriod
https://kotlinlang.org/docs/comparison-to-java.html

**Comment by kekkyojin** [comment]
The existence of Kotlin has nothing to do about making easier the work of coders. Scala -which comes and is compatible with Java- offers a lot of them and it is more robust than Kotlin. Coders of Java could also just use some Java 1.8 features on any Android version thanks to the desugaring feature of Android compiler.

The only reason Kotlin exists and Google keeps pushing it is Oracle’s lawyers and nothing else.

**Comment by Mesum-Hussain** [comment]
I guess everybody understands this philosophy and reasoning and doesn't need it to be explained.

But the issue is that we can't suddenly change the projects getting inspired by some philosophy.
Odysee is a big code base which is as far as I understand a heavily modified fork of the LBRY Android app and it is entirely written in Java. We can definitely right new code in Kotlin, but rewriting the entire code base from scratch again in Kotlin doesn't really make sense.

And I assure you even after 10 years from now Java is going nowhere. There are still going to be apps written in Java unless Google forces everybody to ditch Java entirely. Getting rid of the legacy code is very difficult and requires a lot of effort and manpower.
