### ISSUE TITLE
Video player of center 

### ISSUE THREAD

**Issue by linuxthebaddev** [OdyseeTeam/odysee-android#118]
The video player in not in the middle on full screen mode on my Samsung Galaxy S10 + ![Screenshot_20220209-224135_Odysee.jpg](https://user-images.githubusercontent.com/42673894/153295029-9c3317e0-96ec-4b2d-849a-e01bffd08b5a.jpg)

**Comment by ktprograms** [comment]
![screenshot showing the buttons are the cause](https://user-images.githubusercontent.com/71804605/158963085-fb968ad4-ef1d-4f66-aac4-0b30fac08e96.jpg)

It seems like the space for the home row buttons isn't taken up, as you can see in the screenshot above. (White background added to the Exoplayer view for understanding).

It seems like the space for the status bar is also not filled, that's why the player doesn't go to the top.

**Comment by kekkyojin** [comment]
Is your Galaxy S10+ running Android 11 or newer OS version, @linuxthebaddev ?

**Comment by linuxthebaddev** [comment]
My S10+ is running android 12

**Comment by linuxthebaddev** [comment]
> Is your Galaxy S10+ running Android 11 or newer OS version, @linuxthebaddev ?

My S10+ is running android 12

**Comment by czarkoff** [comment]
FWIW having the same issue on Xiaomi Redmi Note 8 Pro with Android 11.

**Comment by Aryan20** [comment]
Works fine on Redmi note 10 pro with Android 11
