### ISSUE TITLE
Broken Link in the "README.md" File

### ISSUE THREAD

**Issue by decrovert** [OdyseeTeam/odysee-android#173]
In the "README.md" file, there is a broken link to "CONTRIBUTING.md". [Here](https://github.com/OdyseeTeam/odysee-android#contributing) is a link to the place where I found the broken link and below is a screenshot of the area.

![image](https://user-images.githubusercontent.com/99348582/162060195-c00a8606-1164-453c-8428-05e47cc2c9e7.png)

**Comment by ktprograms** [comment]
From the git log, it seems that it was changed in https://github.com/OdyseeTeam/odysee-android/commit/3b08d83fb854f8e5de712b3377197e5ce97fd0a1.

It used to be pointing to https://lbry.io/faq/contributing, but that doesn't mention the `odysee-android` codebase, so perhaps that's why the link was changed.

**Comment by akinwale** [comment]
Fixed. https://github.com/OdyseeTeam/odysee-android/commit/a2259efcba8ad131d0ff4b356ef2abcbc885ff68
